# Reff: http://wiki.ros.org/move_base
recovery_behavior_enabled: true

controller_frequency: 10.0
controller_patience: 10.0
planner_frequency: 5.0
planner_patience: 5.0

conservative_reset_dist: 6.0
oscillation_timeout: 10.0
oscillation_distance: 0.15

# GlobalPlanner:
#   use_voronoi: true  # Enable Voronoi path planning
#   allow_unknown: false  # If your map has unknown areas, set this accordingly
#   use_dijkstra: false  # Switch between Dijkstra or A* search algorithms
#   use_grid_path: false  # Disable regular grid-based planning
#   default_tolerance: 0.5  # Tolerance around the goal
